# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('category_list_id', models.CharField(max_length=16)),
                ('category_list_name', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=16)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=128)),
                ('pageUrl', models.TextField(default='')),
                ('place_id', models.CharField(max_length=16)),
                ('place_zip', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Place'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Place'),
        ),
    ]
