# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 05:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20160603_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
